server:
  port: 8081

spring:
  application:
    name: smart-manufact-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: smart-manufact
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
          workshop: workshop-1
          weight: 100
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8720
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_manufact_order?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smart.manufact.order.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.smart.manufact.order: DEBUG
