server:
  port: 8082

spring:
  application:
    name: smart-manufact-production
  config:
    import:
      - optional:nacos:smart-manufact-production.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: smart-manufact
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        metadata:
          version: 1.0.0
          workshop: workshop-all
          weight: 100
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: smart-manufact
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8721
      eager: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_manufact_production?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smart.manufact.production.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.smart.manufact.production: DEBUG
