server:
  port: 8084

spring:
  application:
    name: smart-manufact-inventory
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: smart-manufact
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
          warehouse: main-warehouse
          weight: 100
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8723
      eager: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_manufact_inventory?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smart.manufact.inventory.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.smart.manufact.inventory: DEBUG
